### ISSUE TITLE
Feature request: custom backlink text

### ISSUE THREAD

**Issue by zblesk** [S73ph4n/joplin_autolinker#3]
Could you please add a config option to customize the text that now says "Linked from"?

**Comment by BsNoSi** [comment]
Would be nice, too, if this Text could be omitted optionally, if for example "[Automatic Backlinks to note](https://discourse.joplinapp.org/t/automatic-backlinks-with-manual-insert-option/13632)" plugin is used.

**Comment by S73ph4n** [comment]
Done. 
V1.0.4 includes a config field to customize the backlink text, and leaving it empty deactivates backlinks.
