### ISSUE TITLE
package is not valid

### ISSUE THREAD

**Issue by tessus** [S73ph4n/joplin_autolinker#4]
For some reason the plugin package file is not valid. Laurent mentioned the following: _This particular version cannot be added to the repo since it's missing a .jpl and manifest file._
The plugin repo updater script always throws an error for the autolinker plugin.

This is also the reason why only version 1.0.0 is in the repo. Any chance you can fix the package and publish again?

**Comment by S73ph4n** [comment]
It's done. 
I've published V1.0.4 with a package that works.
