### ISSUE TITLE
Are there any plans to improve this plugin ?

### ISSUE THREAD

**Issue by bepolymathe** [S73ph4n/joplin_autolinker#6]
Hi @S73ph4n 

The automatic link function is really a need on Joplin but I have the feeling that the use is a bit limited at present. The ideal would surely be to be able to :
- automatic generation of links
- available menu (right click)
- if the user does not want automatic generation, possibility of showing (overlinking) the "unlink"

Do you have any desires to develop this plugin a little more ?
Thank you anyway.
 Have a good day.

**Comment by bepolymathe** [comment]
Ping ?

**Comment by S73ph4n** [comment]
Hey,
As of now, I'm not working on this plugin anymore. I've found that Roman Musin has implemented a better way of inserting links with his [Quick Links plugin](https://discourse.joplinapp.org/t/quick-links-plugin/14214). It has some of the features you're looking for and is more intuitive to use.

**Comment by bepolymathe** [comment]
OK. But it's not an autolinker at all. 🤔
